Enterprise/Models/FriendLink.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Web.Mvc;

namespace Enterprise.Models
{
    public class FriendLink
    {
        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage = "请填写标题")]
        [DisplayName("标题")]
        [StringLength(100, MinimumLength = 2, ErrorMessage = "字符长度只能在2-100之间")]
        public string Title { get; set; }

        [Required(ErrorMessage = "请填写链接地址")]
        [DisplayName("链接地址")]
        public string Site_url { get; set; }

        [DataType(DataType.ImageUrl)]
        [DisplayName("图片")]
        public string Img_url { get; set; }

        [DisplayName("排序")]
        public int? Sort_id { get; set; }

        [DataType(DataType.DateTime)]
        [DisplayFormat(DataFormatString = "{0:d}")]
        [DisplayName("添加时间")]
        public DateTime? Add_time { get; set; }
    }
}

Enterprise/Controllers/FriendLinkController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Enterprise.Models;
using Webdiyer.WebControls.Mvc;

namespace Enterprise.Controllers
{
    [Authorize]
    public class FriendLinkController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: FriendLink
        public ActionResult Index(int pageIndex = 1, string title = null)
        {
            var query = db.FriendLinks.AsQueryable();
            if (!string.IsNullOrWhiteSpace(title))
                query = query.Where(a => a.Title.Contains(title));
            var model = query.OrderByDescending(x => x.Sort_id).ToPagedList(pageIndex, 10);
            return View(model);
        }

        // GET: FriendLink/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FriendLink friendLinkModels = db.FriendLinks.Find(id);
            if (friendLinkModels == null)
            {
                return HttpNotFound();
            }
            return View(friendLinkModels);
        }

        // GET: FriendLink/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: FriendLink/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Title,Site_url,Img_url,Sort_id")] FriendLink friendLinkModels)
        {
            if (ModelState.IsValid)
            {
                if (friendLinkModels.Sort_id == null) friendLinkModels.Sort_id = 0;
                friendLinkModels.Add_time = DateTime.Now;
                db.FriendLinks.Add(friendLinkModels);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(friendLinkModels);
        }

        // GET: FriendLink/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FriendLink friendLinkModels = db.FriendLinks.Find(id);
            if (friendLinkModels == null)
            {
                return HttpNotFound();
            }
            return View(friendLinkModels);
        }

        // POST: FriendLink/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Title,Site_url,Img_url,Sort_id,Add_time")] FriendLink friendLinkModels)
        {
            if (ModelState.IsValid)
            {
                db.Entry(friendLinkModels).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(friendLinkModels);
        }

        // GET: FriendLink/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FriendLink friendLinkModels = db.FriendLinks.Find(id);
            if (friendLinkModels == null)
            {
                return HttpNotFound();
            }
            return View(friendLinkModels);
        }

        // POST: FriendLink/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            FriendLink friendLinkModels = db.FriendLinks.Find(id);
            db.FriendLinks.Remove(friendLinkModels);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Enterprise/Views/FriendLink/Create.cshtml
@model Enterprise.Models.FriendLink

@{
    ViewBag.Title = "添加友情链接";
    Layout = "~/Views/Shared/_Admin_layout.cshtml";
}

@Styles.Render("~/UEditor/webuploadercss")
<style type="text/css">
    #uploader .placeholder .webuploader-pick {
        margin:10px 0;
    }
</style>

<div class="row">
    <div class="col-xs-12">
        <div class="box box-warning">
            <div class="box-header with-border">
                <h3 class="box-title">新建文章</h3>
            </div>
            <div class="box-body">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })


                    <div class="col-xs-12 col-md-6">
                        <div class="form-horizontal">
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                            <div class="form-group">
                                @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-xs-4" })
                                <div class="col-xs-8">
                                    @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Site_url, htmlAttributes: new { @class = "control-label col-xs-4" })
                                <div class="col-xs-8">
                                    @Html.EditorFor(model => model.Site_url, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Site_url, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Sort_id, htmlAttributes: new { @class = "control-label col-xs-4" })
                                <div class="col-xs-8">
                                    @Html.EditorFor(model => model.Sort_id, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Sort_id, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Add_time, htmlAttributes: new { @class = "control-label col-xs-4" })
                                <div class="col-xs-8">
                                    @Html.EditorFor(model => model.Add_time, new { htmlAttributes = new { @class = "form-control wdate", onclick = "WdatePicker()", placeholder = "单击选择日期" } })
                                    @Html.ValidationMessageFor(model => model.Add_time, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>

                    </div>

                    <div class="col-xs-12 col-md-6">
                        <div class="form-horizontal">
                            <div class="form-group">
                                @Html.LabelFor(model => model.Img_url, htmlAttributes: new { @class = "control-label col-xs-4" })
                                <div class="col-xs-8">
                                    <!--头部，相册选择和格式选择-->
                                    <div id="uploader">
                                        <div class="queueList" style="margin:0">
                                            <div id="dndArea" class="placeholder" style="padding-bottom:6px; padding-top:100px;text-align:center;min-height:0;background-position:center 20px;">
                                                <div id="filePicker"></div>
                                            </div>
                                        </div>
                                        <div class="statusBar" style="display:none;">
                                            <div class="progress">
                                                <span class="text">0%</span>
                                                <span class="percentage"></span>
                                            </div><div class="info"></div>
                                            <div class="btns">
                                                <div id="filePicker2"></div><div class="uploadBtn">开始上传</div>
                                            </div>
                                        </div>
                                    </div>
                                    <input type='hidden' name='Img_url' value='' id="imgUrl" />
                                </div>
                            </div>

                        </div>
                    </div>

                    <div class="col-xs-12">
                        <div class="form-horizontal">
                            <div class="form-group">
                                <div class="col-xs-offset-4 col-xs-8">
                                    <input type="submit" value="保存" class="btn btn-warning" />
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>


        </div>
    </div>
</div>



@section PreScripts{
    @Scripts.Render("~/UEditor/webuploaderjs")
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/UEditor/uejs")
    @Scripts.Render("~/WdatePicker/wpjs")
    <script src="~/My97DatePicker/WdatePicker.js"></script>
}

Enterprise/Views/FriendLink/Edit.cshtml
@model Enterprise.Models.FriendLink

@{
    ViewBag.Title = "编辑友情链接";
    Layout = "~/Views/Shared/_Admin_layout.cshtml";
}

@Styles.Render("~/UEditor/webuploadercss")
<style type="text/css">
    #uploader .placeholder .webuploader-pick {
        margin: 0;
    }
</style>

<div class="row">
    <div class="col-xs-12">
        <div class="box box-warning">
            <div class="box-header with-border">
                <h3 class="box-title">编辑友情链接</h3>
            </div>
            <div class="box-body">


                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.Id)




                    <div class="col-xs-12 col-md-6">
                        <div class="form-horizontal">
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                            <div class="form-group">
                                @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-xs-4" })
                                <div class="col-xs-8">
                                    @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Site_url, htmlAttributes: new { @class = "control-label col-xs-4" })
                                <div class="col-xs-8">
                                    @Html.EditorFor(model => model.Site_url, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Site_url, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Sort_id, htmlAttributes: new { @class = "control-label col-xs-4" })
                                <div class="col-xs-8">
                                    @Html.EditorFor(model => model.Sort_id, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Sort_id, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Add_time, htmlAttributes: new { @class = "control-label col-xs-4" })
                                <div class="col-xs-8">
                                    @Html.EditorFor(model => model.Add_time, new { htmlAttributes = new { @class = "form-control wdate", onclick = "WdatePicker()", placeholder = "单击选择日期" } })
                                    @Html.ValidationMessageFor(model => model.Add_time, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>

                    </div>

                    <div class="col-xs-12 col-md-6">
                        <div class="form-horizontal">
                            <div class="form-group">
                                @Html.LabelFor(model => model.Img_url, htmlAttributes: new { @class = "control-label col-xs-4" })
                                <div class="col-xs-8">
                                    <!--头部，相册选择和格式选择-->
                                    <div id="uploader">
                                        <div class="queueList" style="margin:0">
                                            <div id="dndArea" class="placeholder" style="padding-bottom:6px; padding-top:100px;text-align:center;min-height:0;background-position:center 30px;">
                                                <img src="@Model.Img_url" style="margin-top:-90px;padding:0 15px;display:initial" class="img-responsive" />
                                                <div id="filePicker"></div>
                                            </div>
                                        </div>
                                        <div class="statusBar" style="display:none;">
                                            <div class="progress">
                                                <span class="text">0%</span>
                                                <span class="percentage"></span>
                                            </div><div class="info"></div>
                                            <div class="btns">
                                                <div id="filePicker2"></div><div class="uploadBtn">开始上传</div>
                                            </div>
                                        </div>
                                    </div>
                                    <input type='hidden' name='Img_url' value='@Model.Img_url' id="imgUrl" />
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-xs-12">
                        <div class="form-horizontal">
                            <div class="form-group">
                                <div class="col-xs-offset-4 col-xs-8">
                                    <input type="submit" value="保存" class="btn btn-warning" />
                                </div>
                            </div>
                        </div>

                    </div>

                }

            </div>
        </div>
    </div>
</div>
@section PreScripts{
    @Scripts.Render("~/UEditor/webuploaderjs")

    <script type="text/javascript">
        $("#categoryId option").each(function () {
            if ($(this).text() == "@ViewBag.CategoryTitle") {
                $(this).attr("selected", "selected");
            }
        })
    </script>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/UEditor/uejs")
    @Scripts.Render("~/WdatePicker/wpjs")
    <script src="~/My97DatePicker/WdatePicker.js"></script>
}

Enterprise/Views/FriendLink/Index.cshtml
@model PagedList<Enterprise.Models.FriendLink>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Admin_layout.cshtml";
}
<style type="text/css">
    .pagination{margin:0;}
</style>

<div class="row">
    <div class="col-xs-12">
        <div class="box box-warning">
            <div class="box-header with-border">
                <h3 class="box-title">友情链接</h3>
            </div>
            <div class="box-body">
                <div class="table-responsive">
                    <table class="table no-margin">
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.Img_url)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Title)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Site_url)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Sort_id)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Add_time)
                            </th>
                            <th>操作</th>
                        </tr>

                        @foreach (var item in Model)
                        {
                            <tr>
                                <td height="50">
                                    <img src="@item.Img_url" width="50" />
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Title)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Site_url)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Sort_id)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Add_time)
                                </td>

                                <td>
                                    @using (Html.BeginForm("Delete", "FriendLink", new { id = item.Id }))
                                    {
                                        @Html.AntiForgeryToken()
                                        @Html.ActionLink("编辑", "Edit", new { id = item.Id }, new { @class = "btn btn-xs btn-info" })@:&nbsp;
                                        <input type="submit" class="btn btn-xs btn-danger" value="删除" />
                                    }
                                </td>
                            </tr>
                        }
                    </table>
                </div>
            </div>

            <div class="box-footer clearfix">
                @Html.ActionLink("添加友情链接", "Create", null, new { @class = "btn btn-sm btn-info btn-flat pull-left" })
                @Html.Pager(Model, new PagerOptions { PageIndexParameterName = "pageIndex", ContainerTagName = "ul", CssClass = "pagination pagination-sm inline pull-right", CurrentPagerItemTemplate = "<li class=\"active\"><a href=\"#\">{0}</a></li>", DisabledPagerItemTemplate = "<li class=\"disabled\"><a>{0}</a></li>", PagerItemTemplate = "<li>{0}</li>", Id = "bootstrappager" })
            </div>


        </div>
    </div>
</div>

@section PreScripts{
    @Scripts.Render("~/bundles/jquery")
    <script type="text/javascript">
        //删除条目时弹出提示框
        $(function () {
            $("input.btn-danger").click(function () {
                if (!confirm("确定要删除吗？")) window.event.returnValue = false;
            })
        })
    </script>
}