Enterprise/Controllers/AdminController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Xml.Linq;
using System.Collections.Generic;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using Enterprise.Models;
using Microsoft.Win32;

namespace Enterprise.Controllers
{
    [Authorize]
    public class AdminController : Controller
    {
        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;
        private ApplicationDbContext db = new ApplicationDbContext();

        public AdminController()
        {
        }

        public AdminController(ApplicationUserManager userManager, ApplicationSignInManager signInManager)
        {
            UserManager = userManager;
            SignInManager = signInManager;
        }

        public ApplicationSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            }
            private set
            {
                _signInManager = value;
            }
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        //
        // GET: /Manage/Index
        public async Task<ActionResult> Index(ManageMessageId? message)
        {
            ViewBag.StatusMessage =
                message == ManageMessageId.ChangePasswordSuccess ? "Your password has been changed."
                : message == ManageMessageId.SetPasswordSuccess ? "Your password has been set."
                : message == ManageMessageId.SetTwoFactorSuccess ? "Your two-factor authentication provider has been set."
                : message == ManageMessageId.Error ? "An error has occurred."
                : message == ManageMessageId.AddPhoneSuccess ? "Your phone number was added."
                : message == ManageMessageId.RemovePhoneSuccess ? "Your phone number was removed."
                : "";

            var userId = User.Identity.GetUserId();
            var model = new IndexViewModel
            {
                HasPassword = HasPassword(),
                PhoneNumber = await UserManager.GetPhoneNumberAsync(userId),
                TwoFactor = await UserManager.GetTwoFactorEnabledAsync(userId),
                Logins = await UserManager.GetLoginsAsync(userId),
                BrowserRemembered = await AuthenticationManager.TwoFactorBrowserRememberedAsync(userId)
            };
            return View(model);
        }

        //
        // POST: /Manage/RemoveLogin
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> RemoveLogin(string loginProvider, string providerKey)
        {
            ManageMessageId? message;
            var result = await UserManager.RemoveLoginAsync(User.Identity.GetUserId(), new UserLoginInfo(loginProvider, providerKey));
            if (result.Succeeded)
            {
                var user = await UserManager.FindByIdAsync(User.Identity.GetUserId());
                if (user != null)
                {
                    await SignInManager.SignInAsync(user, isPersistent: false, rememberBrowser: false);
                }
                message = ManageMessageId.RemoveLoginSuccess;
            }
            else
            {
                message = ManageMessageId.Error;
            }
            return RedirectToAction("ManageLogins", new { Message = message });
        }

        //
        // GET: /Manage/AddPhoneNumber
        public ActionResult AddPhoneNumber()
        {
            return View();
        }

        //
        // POST: /Manage/AddPhoneNumber
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> AddPhoneNumber(AddPhoneNumberViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            // Generate the token and send it
            var code = await UserManager.GenerateChangePhoneNumberTokenAsync(User.Identity.GetUserId(), model.Number);
            if (UserManager.SmsService != null)
            {
                var message = new IdentityMessage
                {
                    Destination = model.Number,
                    Body = "Your security code is: " + code
                };
                await UserManager.SmsService.SendAsync(message);
            }
            return RedirectToAction("VerifyPhoneNumber", new { PhoneNumber = model.Number });
        }

        //
        // POST: /Manage/EnableTwoFactorAuthentication
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> EnableTwoFactorAuthentication()
        {
            await UserManager.SetTwoFactorEnabledAsync(User.Identity.GetUserId(), true);
            var user = await UserManager.FindByIdAsync(User.Identity.GetUserId());
            if (user != null)
            {
                await SignInManager.SignInAsync(user, isPersistent: false, rememberBrowser: false);
            }
            return RedirectToAction("Index", "Manage");
        }

        //
        // POST: /Manage/DisableTwoFactorAuthentication
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DisableTwoFactorAuthentication()
        {
            await UserManager.SetTwoFactorEnabledAsync(User.Identity.GetUserId(), false);
            var user = await UserManager.FindByIdAsync(User.Identity.GetUserId());
            if (user != null)
            {
                await SignInManager.SignInAsync(user, isPersistent: false, rememberBrowser: false);
            }
            return RedirectToAction("Index", "Manage");
        }

        //
        // GET: /Manage/VerifyPhoneNumber
        public async Task<ActionResult> VerifyPhoneNumber(string phoneNumber)
        {
            var code = await UserManager.GenerateChangePhoneNumberTokenAsync(User.Identity.GetUserId(), phoneNumber);
            // Send an SMS through the SMS provider to verify the phone number
            return phoneNumber == null ? View("Error") : View(new VerifyPhoneNumberViewModel { PhoneNumber = phoneNumber });
        }

        //
        // POST: /Manage/VerifyPhoneNumber
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> VerifyPhoneNumber(VerifyPhoneNumberViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            var result = await UserManager.ChangePhoneNumberAsync(User.Identity.GetUserId(), model.PhoneNumber, model.Code);
            if (result.Succeeded)
            {
                var user = await UserManager.FindByIdAsync(User.Identity.GetUserId());
                if (user != null)
                {
                    await SignInManager.SignInAsync(user, isPersistent: false, rememberBrowser: false);
                }
                return RedirectToAction("Index", new { Message = ManageMessageId.AddPhoneSuccess });
            }
            // If we got this far, something failed, redisplay form
            ModelState.AddModelError("", "Failed to verify phone");
            return View(model);
        }

        //
        // GET: /Manage/RemovePhoneNumber
        public async Task<ActionResult> RemovePhoneNumber()
        {
            var result = await UserManager.SetPhoneNumberAsync(User.Identity.GetUserId(), null);
            if (!result.Succeeded)
            {
                return RedirectToAction("Index", new { Message = ManageMessageId.Error });
            }
            var user = await UserManager.FindByIdAsync(User.Identity.GetUserId());
            if (user != null)
            {
                await SignInManager.SignInAsync(user, isPersistent: false, rememberBrowser: false);
            }
            return RedirectToAction("Index", new { Message = ManageMessageId.RemovePhoneSuccess });
        }

        //
        // GET: /Manage/ChangePassword
        public ActionResult ChangePassword()
        {
            return View();
        }

        //
        // POST: /Manage/ChangePassword
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> ChangePassword(ChangePasswordViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            var result = await UserManager.ChangePasswordAsync(User.Identity.GetUserId(), model.OldPassword, model.NewPassword);
            if (result.Succeeded)
            {
                var user = await UserManager.FindByIdAsync(User.Identity.GetUserId());
                if (user != null)
                {
                    await SignInManager.SignInAsync(user, isPersistent: false, rememberBrowser: false);
                }
                return RedirectToAction("Index", "Account", new { Message = ManageMessageId.ChangePasswordSuccess });
            }
            AddErrors(result);
            return View(model);
        }

        //
        // GET: /Manage/SetPassword
        public ActionResult SetPassword()
        {
            return View();
        }

        //
        // POST: /Manage/SetPassword
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> SetPassword(SetPasswordViewModel model)
        {
            if (ModelState.IsValid)
            {

Enterprise/Controllers/ArticleController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.IO;
using Enterprise.Models;
using Webdiyer.WebControls.Mvc;
using Microsoft.Security.Application;

namespace Enterprise.Controllers
{
    [Authorize]
    public class ArticleController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Article
        public ActionResult Index(int pageIndex = 1, string Call_index = null)
        {
            var query = db.Articles.AsQueryable();
            if (!string.IsNullOrWhiteSpace(Call_index))
                query = query.Where(x=>x.ArticleCategory.Call_index==Call_index);
            var model = query.OrderByDescending(x => x.Id).ToPagedList(pageIndex, 10);
            return View(model);
        }


        // GET: Article/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Article article = db.Articles.Find(id);
            if (article == null)
            {
                return HttpNotFound();
            }
            return View(article);
        }

        // GET: Article/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Article/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Title,Sub_title,Call_index,Img_url,Zhaiyao,Content,Remark,Seo_title,Seo_keyword,Seo_description,Click,Tag,Add_time,Update_time")] Article article, int? categoryId)
        {
            if (ModelState.IsValid)
            {
                if (categoryId != null)
                {
                    article.ArticleCategory = db.ArticleCategories.Find(categoryId);
                }
                if (article.Add_time == null)
                {
                    article.Add_time = DateTime.Now;
                }
                if(article.Click==null)
                {
                    article.Click = 0;
                }
                if(String.IsNullOrEmpty(article.Seo_title))
                {
                    article.Seo_title = article.Title;
                }
                //过滤XSS
                article.Content = Sanitizer.GetSafeHtmlFragment(article.Content);
                article.Author = User.Identity.Name;
                db.Articles.Add(article);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(article);
        }

        // GET: Article/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Article article = db.Articles.Find(id);
            if (article == null)
            {
                return HttpNotFound();
            }
            if (article.ArticleCategory == null)
            {
                ViewBag.CategoryTitle = "";
            }
            else
            {
                ViewBag.CategoryTitle = article.ArticleCategory.Title;
            }
            return View(article);
        }

        // POST: Article/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Title,Sub_title,Call_index,Img_url,Zhaiyao,Content,Remark,Seo_title,Seo_keyword,Seo_description,Click,Tag,Add_time,Update_time")] Article article, int? categoryId)
        {
            if (ModelState.IsValid)
            {
                Article tempArticle = db.Articles.Find(article.Id);
                if (categoryId != null)
                {
                    tempArticle.ArticleCategory = db.ArticleCategories.Find(categoryId);
                }
                tempArticle.Title = article.Title;
                tempArticle.Sub_title = article.Sub_title;
                tempArticle.Img_url = article.Img_url;
                tempArticle.Zhaiyao = article.Zhaiyao;
                tempArticle.Content = Sanitizer.GetSafeHtmlFragment(article.Content);
                tempArticle.Remark = article.Remark;
                tempArticle.Seo_title = article.Seo_title;
                tempArticle.Seo_keyword = article.Seo_keyword;
                tempArticle.Seo_description = article.Seo_description;
                tempArticle.Add_time = article.Add_time;
                tempArticle.Click = article.Click;
                tempArticle.Tag = article.Tag;
                tempArticle.Call_index = article.Call_index;
                tempArticle.Update_time = DateTime.Now;
                db.Entry(tempArticle).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(article);
        }

        // GET: Article/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Article article = db.Articles.Find(id);
            if (article == null)
            {
                return HttpNotFound();
            }
            return View(article);
        }

        // POST: Article/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Article article = db.Articles.Find(id);
            db.Articles.Remove(article);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        //百度webupload上传控件
        public ActionResult UpLoadProcess(string id, HttpPostedFileBase file)
        {
            string filePathName = string.Empty;

            string localPath = Path.Combine(HttpRuntime.AppDomainAppPath, "Content\\Images");
            if (Request.Files.Count == 0)
            {
                return Json(new { jsonrpc = 2.0, error = new { code = 102, message = "保存失败" }, id = "id" });
            }

            string ex = Path.GetExtension(file.FileName);
            filePathName = Guid.NewGuid().ToString("N") + ex;
            if (!System.IO.Directory.Exists(localPath))
            {
                System.IO.Directory.CreateDirectory(localPath);
            }
            file.SaveAs(Path.Combine(localPath, filePathName));

            return Json(new { jsonrpc = "2.0", id = id, filePath = "/Content/Images/" + filePathName });
        }

        //文章分类
        [ChildActionOnly]
        public ActionResult Category()
        {
            IList<ArticleCategory> categories = db.ArticleCategories.ToList();
            return PartialView("_Category", categories);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

// 

Enterprise/Views/Article/Index.cshtml
@model PagedList<Enterprise.Models.Article>

@{
    ViewBag.Title = "Index";
}

<div class="row">
    <div class="col-xs-12">
        <div class="box box-warning">
            <div class="box-header with-border">

                    <h3 class="box-title">文章列表</h3>

                    <div class="pull-right col-xs-6 col-md-3">
                        @Html.Action("GetArticleCategories","Admin")
                    </div>

            </div>
            <div class="box-body">
                <div class="table-responsive">
                    <table class="table no-margin">
                        <tr>
                            <th width="10%">
                                @Html.DisplayNameFor(model => model.Img_url)
                            </th>
                            <th width="30%">
                                @Html.DisplayNameFor(model => model.Title)
                            </th>
                            <th width="15%">
                                @Html.DisplayNameFor(model => model.ArticleCategory)
                            </th>
                            <th width="10%">
                                @Html.DisplayNameFor(model => model.Click)
                            </th>
                            <th width="20%">
                                @Html.DisplayNameFor(model => model.Add_time)
                            </th>
                            <th>操作</th>
                        </tr>

                        @foreach (var item in Model)
                        {
                            <tr>
                                <td height="50">
                                    <img src="@item.Img_url" width="40" />
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Title)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.ArticleCategory.Title)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Click)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Add_time)
                                </td>
                                <td>
                                    @using (Html.BeginForm("Delete", "Article", new { id = item.Id }))
                                    {
                                        @Html.AntiForgeryToken()
                                        @Html.ActionLink("编辑", "Edit", new { id = item.Id }, new { @class = "btn btn-xs btn-info" })@:&nbsp;
                                        <input type="submit" class="btn btn-xs btn-danger" value="删除" />
                                    }
                                </td>
                            </tr>
                        }
                    </table>
                </div>
            </div>
            <div class="box-footer">
                @Html.Pager(Model, new PagerOptions { PageIndexParameterName = "pageIndex", ContainerTagName = "ul", CssClass = "pagination pagination-sm inline", CurrentPagerItemTemplate = "<li class=\"active\"><a href=\"#\">{0}</a></li>", DisabledPagerItemTemplate = "<li class=\"disabled\"><a>{0}</a></li>", PagerItemTemplate = "<li>{0}</li>", Id = "bootstrappager" })
            </div>
        </div>
    </div>
</div>

@section PreScripts{
    @Scripts.Render("~/bundles/jquery")
    <script type="text/javascript">

        
        $(function () {

            //删除条目时弹出提示框
            $("input.btn-danger").click(function () {
                if (!confirm("确定要删除吗？")) window.event.returnValue = false;
            })

            //选择框改变，提交表单
            $("#Call_index").change(function(){
                $("#search").submit();
            })

            //选择框定位
            var call_index = '@Request.QueryString["Call_index"]';
            $("#Call_index option").each(function () {
                if($(this).val()==call_index)
                {
                    $(this).attr("selected","selected");
                }
            })
        })



    </script>
}

Enterprise/Views/Article/_Category.cshtml
@model IEnumerable<Enterprise.Models.ArticleCategory>

<label class="control-label col-xs-4"> 文章分类</label>
<div class="col-xs-8">
    @Html.DropDownList("categoryId", new SelectList(Model, "Id", "Title"), "请选择...", new { @class="form-control"})
</div>
