Enterprise/Models/ArticleCategory.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Enterprise.Models
{
    public class ArticleCategory
    {
        public int Id { get; set; }

        [Required(ErrorMessage="请输入分类名称")]
        [StringLength(100, MinimumLength = 2, ErrorMessage = "字符长度只能在2-100之间")]
        [DisplayName("名称")]
        public string Title { get; set; }

        [StringLength(100, MinimumLength = 2, ErrorMessage = "字符长度只能在2-100之间")]
        [RegularExpression("^[A-Za-z0-9]+$",ErrorMessage="必须由字母或者是数字组成")]
        [DisplayName("调用名称")]
        public string Call_index { get; set; }

        [DisplayName("SEO标题")]
        public string Seo_title { get; set; }

        [DataType(DataType.MultilineText)]
        [DisplayName("SEO关键词")]
        public string Seo_keyword { get; set; }

        [DataType(DataType.MultilineText)]
        [DisplayName("SEO描述")]
        public string Seo_description { get; set; }

        [DisplayName("分类描述")]
        [DataType(DataType.MultilineText)]
        public string Description { get; set; }

        [DisplayName("文章")]
        public virtual ICollection<Article> Articles { get; set; }
    }
}

Enterprise/Controllers/ArticleCategoryController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Enterprise.Models;

namespace Enterprise.Controllers
{
    [Authorize]
    public class ArticleCategoryController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: ArticleCategory
        public ActionResult Index()
        {
            return View(db.ArticleCategories.ToList());
        }

        // GET: ArticleCategory/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ArticleCategory articleCategory = db.ArticleCategories.Find(id);
            if (articleCategory == null)
            {
                return HttpNotFound();
            }
            return View(articleCategory);
        }

        // GET: ArticleCategory/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ArticleCategory/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Title,Call_index,Seo_title,Seo_keyword,Seo_description,Description")] ArticleCategory articleCategory)
        {
            if (ModelState.IsValid)
            {
                db.ArticleCategories.Add(articleCategory);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(articleCategory);
        }

        // GET: ArticleCategory/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ArticleCategory articleCategory = db.ArticleCategories.Find(id);
            if (articleCategory == null)
            {
                return HttpNotFound();
            }
            return View(articleCategory);
        }

        // POST: ArticleCategory/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Title,Call_index,Seo_title,Seo_keyword,Seo_description,Description")] ArticleCategory articleCategory)
        {
            if (ModelState.IsValid)
            {
                db.Entry(articleCategory).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(articleCategory);
        }

        // GET: ArticleCategory/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ArticleCategory articleCategory = db.ArticleCategories.Find(id);
            if (articleCategory == null)
            {
                return HttpNotFound();
            }
            return View(articleCategory);
        }

        // POST: ArticleCategory/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ArticleCategory articleCategory = db.ArticleCategories.Find(id);
            db.ArticleCategories.Remove(articleCategory);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

// 

Enterprise/Views/ArticleCategory/Create.cshtml
@model Enterprise.Models.ArticleCategory

@{
    ViewBag.Title = "Create";
}

<div class="row">
    <div class="col-xs-12">
        <div class="box box-warning">
            <div class="box-header with-border">
                <h3 class="box-title">新建分类</h3>
            </div>
            <div class="box-body">


                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-xs-4" })
                            <div class="col-xs-8 col-md-5">
                                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Call_index, htmlAttributes: new { @class = "control-label col-xs-4" })
                            <div class="col-xs-8 col-md-5">
                                @Html.EditorFor(model => model.Call_index, new { htmlAttributes = new { @class = "form-control" ,placeholder="字母或者是数字组成"} })
                                @Html.ValidationMessageFor(model => model.Call_index, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Seo_title, htmlAttributes: new { @class = "control-label col-xs-4" })
                            <div class="col-xs-8 col-md-5">
                                @Html.EditorFor(model => model.Seo_title, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Seo_title, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Seo_keyword, htmlAttributes: new { @class = "control-label col-xs-4" })
                            <div class="col-xs-8 col-md-5">
                                @Html.EditorFor(model => model.Seo_keyword, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Seo_keyword, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Seo_description, htmlAttributes: new { @class = "control-label col-xs-4" })
                            <div class="col-xs-8 col-md-5">
                                @Html.EditorFor(model => model.Seo_description, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Seo_description, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-xs-4" })
                            <div class="col-xs-8 col-md-5">
                                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-xs-offset-4 col-xs-8">
                                <input type="submit" value="保存" class="btn btn-warning" />
                            </div>
                        </div>
                    </div>
                }
            </div>

        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Enterprise/Views/ArticleCategory/Edit.cshtml
@model Enterprise.Models.ArticleCategory

@{
    ViewBag.Title = "Edit";
}

<div class="row">
    <div class="col-xs-12">
        <div class="box box-warning">
            <div class="box-header with-border">
                <h3 class="box-title">编辑分类</h3>
            </div>
            <div class="box-body">

                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.Id)

                        <div class="form-group">
                            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-xs-4" })
                            <div class="col-xs-8 col-md-5">
                                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Call_index, htmlAttributes: new { @class = "control-label col-xs-4" })
                            <div class="col-xs-8 col-md-5">
                                @Html.EditorFor(model => model.Call_index, new { htmlAttributes = new { @class = "form-control" , placeholder="字母或者是数字组成"} })
                                @Html.ValidationMessageFor(model => model.Call_index, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Seo_title, htmlAttributes: new { @class = "control-label col-xs-4" })
                            <div class="col-xs-8 col-md-5">
                                @Html.EditorFor(model => model.Seo_title, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Seo_title, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Seo_keyword, htmlAttributes: new { @class = "control-label col-xs-4" })
                            <div class="col-xs-8 col-md-5">
                                @Html.EditorFor(model => model.Seo_keyword, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Seo_keyword, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Seo_description, htmlAttributes: new { @class = "control-label col-xs-4" })
                            <div class="col-xs-8 col-md-5">
                                @Html.EditorFor(model => model.Seo_description, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Seo_description, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-xs-4" })
                            <div class="col-xs-8 col-md-5">
                                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-xs-offset-4 col-xs-8">
                                <input type="submit" value="保存" class="btn btn-warning" />
                            </div>
                        </div>
                    </div>
                }

            </div>

        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Enterprise/Views/ArticleCategory/Index.cshtml
@model IEnumerable<Enterprise.Models.ArticleCategory>

@{
    ViewBag.Title = "Index";
}


<div class="row">
    <div class="col-xs-12">
        <div class="box box-warning">
            <div class="box-header with-border">
                <h3 class="box-title">文章分类列表</h3>
            </div>
            <div class="box-body">
                <div class="table-responsive">
                    <table class="table no-margin">
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.Title)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Call_index)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Seo_title)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Description)
                            </th>
                            <th>操作</th>
                        </tr>

                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Title)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Call_index)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Seo_title)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Description)
                                </td>
                                <td>
                                    @using (Html.BeginForm("Delete", "ArticleCategory", new { id = item.Id }))
                                    {
                                        @Html.AntiForgeryToken()
                                        @Html.ActionLink("编辑", "Edit", new { id = item.Id }, new { @class = "btn btn-xs btn-info" })@:&nbsp;
                                        <input type="submit" class="btn btn-xs btn-danger" value="删除" />
                                    }
                                </td>
                            </tr>
                        }
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@section PreScripts{
    @Scripts.Render("~/bundles/jquery")
    <script type="text/javascript">
                //删除条目时弹出提示框
            $(function () {
                $("input.btn-danger").click(function () {
                    if (!confirm("确定要删除吗？")) window.event.returnValue = false;
                })
            })
    </script>
}